### ISSUE TITLE
Clarify Worker API usage

### ISSUE THREAD

**Issue by SootyOwl** [sivulich/mqttasgi#11]
Hi,

I've been really happy with the basic usage of mqttasgi in my project, however I'm struggling to understand how to use the worker API.

I'm attempting to use spawn_worker so I can handle different subscriptions/topics in different consumers.

```py
# try to spawn a worker
await self.spawn_worker(
    app_id=123,
    consumer_path="server.consumers:MQTTConsumer",
    consumer_params={"mqttTopics": ['dt/#']},
)
```

However, this call always produces an exception:
```
2022-08-24 12:42:30,687 ERROR    [mqttasgi][app][send] - Exception of 0
2022-08-24 12:42:30,687 ERROR    MQTTConsumer.__init__() got an unexpected keyword argument 'receive'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mqttasgi/server.py", line 309, in _application_send
    await action_map[msg['type']](app_id, msg)
  File "/usr/local/lib/python3.10/site-packages/mqttasgi/server.py", line 276, in mqttasgi_worker_spawn
    self.create_application(new_app_id, consumer_path=new_consumer_path,
  File "/usr/local/lib/python3.10/site-packages/mqttasgi/server.py", line 349, in create_application
    self.application_data[app_id]['instance'] = application(scope,
TypeError: MQTTConsumer.__init__() got an unexpected keyword argument 'receive'
```

I've attempted to dig into the code but I've not been able to understand where I'm going wrong here. This error also happens if I attempt to use the provided 'TestMqttConsumer' class and send it a message on the `spawn` topic:

```
[2022-08-24 12:52:47] DEBUG [mqttasgi.consumers:97] [mqttasgi][consumer][connect] - Connected!
[2022-08-24 12:52:47] DEBUG [mqttasgi.cli:200] [mqttasgi][app][subscribe] - Subscription to spawn:1
[2022-08-24 12:52:47] DEBUG [mqttasgi.cli:200] [mqttasgi][app][subscribe] - Subscription to kill:1
[2022-08-24 12:53:05] DEBUG [mqttasgi.cli:142] [mqttasgi][mqtt][receive] - Added message to queue app_ids:{0} topic:spawn
[2022-08-24 12:53:05] DEBUG [mqttasgi.consumers:110] [mqttasgi][consumer][receive] - Received spawn:b'123'
[2022-08-24 12:53:05] ERROR [mqttasgi.cli:311] [mqttasgi][app][send] - Exception of 0
[2022-08-24 12:53:05] ERROR [mqttasgi.cli:313] MqttConsumer.__init__() got an unexpected keyword argument 'receive'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mqttasgi/server.py", line 309, in _application_send
    await action_map[msg['type']](app_id, msg)
  File "/usr/local/lib/python3.10/site-packages/mqttasgi/server.py", line 276, in mqttasgi_worker_spawn
    self.create_application(new_app_id, consumer_path=new_consumer_path,
  File "/usr/local/lib/python3.10/site-packages/mqttasgi/server.py", line 349, in create_application
    self.application_data[app_id]['instance'] = application(scope,
TypeError: MqttConsumer.__init__() got an unexpected keyword argument 'receive'
```

I understand that the worker API is experimental at the moment, but can you point me in the right direction/clarify the usage of this feature?

Thanks

**Comment by sivulich** [comment]
Hi @SootyOwl thanks for your comments.

Your usage is correct, I think it's related to a possible bug here:
[line 12 of utils.py](https://github.com/sivulich/mqttasgi/blob/bcf4262031f5155647a1acd36a283528f1199588/mqttasgi/utils.py#L12)

I think it should be:
```python
    return application.as_asgi()
```

Let me know if that change works for you and I'll create a PR with the fix.

**Comment by SootyOwl** [comment]
Hi @sivulich

I tried the change above but was presented with another exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/mqttasgi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/mqttasgi/cli.py", line 41, in main
    application = get_application(args.application)
  File "/usr/local/lib/python3.10/site-packages/mqttasgi/utils.py", line 13, in get_application
    return application.as_asgi()
AttributeError: 'ProtocolTypeRouter' object has no attribute 'as_asgi'
```

I managed to "solve" this problem by changing https://github.com/sivulich/mqttasgi/blob/bcf4262031f5155647a1acd36a283528f1199588/mqttasgi/utils.py#L12 to 

```python
    if hasattr(application, 'as_asgi'):
        return application.as_asgi()
    return application
```

This doesn't present any errors, and a worker now successfully spawns!

```
DEBUG [mqttasgi.cli:208] [mqttasgi][app][subscribe] - Subscription to dt/#:0 has 2 listeners
```
