### ISSUE TITLE
Error when importing models in consumers.py - Apps aren't loaded yet

### ISSUE THREAD

**Issue by ThinkTransit** [sivulich/mqttasgi#13]
Hi,
Great project.
Not sure if this is a bug or not. Your sample code works perfectly for me however when I try and import a model (to save MQTT message to DB) I get an error.

**consumers.py**
```
from mqttasgi.consumers import MqttConsumer
from .models import MQTTMessage

class MyMqttConsumer(MqttConsumer):

    async def connect(self):
        await self.subscribe('#', 2)

    async def receive(self, mqtt_message):
        m = MQTTMessage()
        m.topic = mqtt_message['topic']
        m.payload = mqtt_message['payload']
        m.qos = mqtt_message['qos']
        m.save()

    async def disconnect(self):
        await self.unsubscribe('#')
```
**Error**
```
mqttasgi -H localhost -p 1883 iot_platform.asgi:application

Traceback (most recent call last):
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/django/utils/translation/trans_real.py", line 210, in _add_installed_apps_translations
    app_configs = reversed(apps.get_app_configs())
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/django/apps/registry.py", line 147, in get_app_configs
    self.check_apps_ready()
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/bin/mqttasgi", line 33, in <module>
    sys.exit(load_entry_point('mqttasgi==1.1.1', 'console_scripts', 'mqttasgi')())
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/mqttasgi/cli.py", line 41, in main
    application = get_application(args.application)
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/mqttasgi/utils.py", line 8, in get_application
    application = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/patrick/django/iot_platform/./iot_platform/asgi.py", line 14, in <module>
    from external_api.consumers import MyMqttConsumer
  File "/home/patrick/django/iot_platform/./external_api/consumers.py", line 6, in <module>
    class MQTTMessage(models.Model):
  File "/home/patrick/django/iot_platform/./external_api/consumers.py", line 7, in MQTTMessage
    class Meta:
  File "/home/patrick/django/iot_platform/./external_api/consumers.py", line 8, in Meta
    verbose_name = _("MQTT Message")
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 95, in gettext
    return _trans.gettext(message)
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/django/utils/translation/trans_real.py", line 374, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/django/utils/translation/trans_real.py", line 287, in translation
    _translations[language] = DjangoTranslation(language)
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/django/utils/translation/trans_real.py", line 164, in __init__
    self._add_installed_apps_translations()
  File "/home/patrick/.local/share/virtualenvs/iot_platform-NhBFDZeq/lib/python3.10/site-packages/django/utils/translation/trans_real.py", line 212, in _add_installed_apps_translations
    raise AppRegistryNotReady(
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.

```

**Comment by ThinkTransit** [comment]
Nevermind I figured this out, the model save needs to be in a different method. Posting full code below as it might help others.

```
from mqttasgi.consumers import MqttConsumer
from asgiref.sync import sync_to_async


class MyMqttConsumer(MqttConsumer):

    async def connect(self):
        await self.subscribe('#', 2)

    async def receive(self, mqtt_message):
        await self.save_message(mqtt_message)

    async def disconnect(self):
        await self.unsubscribe('#')

    @sync_to_async
    def save_message(self, mqtt_message):
        from .models import MQTTMessage
        m = MQTTMessage()
        m.topic = mqtt_message['topic']
        m.payload = mqtt_message['payload']
        m.qos = mqtt_message['qos']
        m.save()
```
