### ISSUE TITLE
Error with multiple subscriptions to the same topic and different QoS

### ISSUE THREAD

**Issue by mzitelli97** [sivulich/mqttasgi#25]
When multiple applications subscribe to the same topic with different QoS values, the messages are not being processed.
The problem might be in the mqtt_subscribe() function of server.py when trying to update the status of the current subscription.

**Comment by tlifschitz** [comment]
Hi all, let me provide some logs

Two subscribers with the same qos level:

```
INFO     [mqttasgi][connection][connected] - Connected to 172.31.17.149:1883
DEBUG    [mqttasgi][app][subscribe] - Subscription to networks/+/devices/gateways/+/properties/+:2
DEBUG    [mqttasgi][app][subscribe] - Subscription to networks/+/devices/gateways/+/properties/+:2 has 2 listeners
```

Two subscribers with different qos level:

```
INFO     [mqttasgi][connection][connected] - Connected to 172.31.17.149:1883
DEBUG    [mqttasgi][app][subscribe] - Subscription to networks/+/devices/gateways/+/properties/+:1
DEBUG    [mqttasgi][app][subscribe] - Subscription to networks/+/devices/gateways/+/properties/+ must be updated to QOS: 2
ERROR    [mqttasgi][app][send] - Exception of diagnosticsConsumer-app-0
			Traceback (most recent call last):
			  File "/home/ubuntu/workspace/serverV2/maper_projects/mqttasgi/server.py", line 296, in _application_send
			    await action_map[msg['type']](app_id, msg)
			  File "/home/ubuntu/workspace/serverV2/maper_projects/mqttasgi/server.py", line 185, in mqtt_subscribe
			    status = (qos, status[1])
			KeyError: 1```

**Comment by tlifschitz** [comment]
With the fix the subscription with higher qos succeeds:

```
INFO     [mqttasgi][connection][connected] - Connected to 172.31.17.149:1883
DEBUG    [mqttasgi][app][subscribe] - Subscription to networks/+/devices/gateways/+/properties/+:1
DEBUG    [mqttasgi][app][subscribe] - Subscription to networks/+/devices/gateways/+/properties/+ must be updated to QOS: 2
```
